name: node-server CI

on:
  push:
    branches:
      - master
      - staging
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  DOCKERHUB_ORG: 'scribear'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_ORG }}/frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_ORG }}/frontend:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_ORG }}/frontend:buildcache,mode=max
          build-args: |
            BRANCH=${{ steps.meta.outputs.version }}
            BUILDNUMBER=${{ github.run_number }}
            ARG GITSHA1=${{ github.sha }}